// Generated by CoffeeScript 1.9.3
(function() {
  var Board, HEADING, drawHelper, makeWalls;

  HEADING = require('./core').HEADING;

  drawHelper = require('./draw');

  makeWalls = require('./defaultBoard');

  module.exports = Board = (function() {
    function Board() {
      var i, j, ref, ref1, row, walls, x, y;
      this.possibleTargetLocations = [];
      this.targetLoc = null;
      this.width = 16;
      this.height = 16;
      this.squares = [];
      for (x = i = 0, ref = this.width - 1; 0 <= ref ? i <= ref : i >= ref; x = 0 <= ref ? ++i : --i) {
        row = [];
        for (y = j = 0, ref1 = this.height - 1; 0 <= ref1 ? j <= ref1 : j >= ref1; y = 0 <= ref1 ? ++j : --j) {
          walls = [];
          if (x === 0) {
            walls.push(HEADING.WEST);
          }
          if (y === 0) {
            walls.push(HEADING.NORTH);
          }
          if (x === this.width - 1) {
            walls.push(HEADING.EAST);
          }
          if (y === this.height - 1) {
            walls.push(HEADING.SOUTH);
          }
          row.push(walls);
        }
        this.squares.push(row);
      }
      makeWalls(this);
    }

    Board.prototype.draw = function(robots) {
      return drawHelper(this, robots);
    };

    return Board;

  })();

}).call(this);
