// Generated by CoffeeScript 1.9.3
(function() {
  var EAST, HEADING, NORTH, OPPOSITE_SIDES, SOUTH, TARGETS, WALLS, WEST, makeWallPair, nextCoord, ref;

  ref = require('./core'), HEADING = ref.HEADING, nextCoord = ref.nextCoord;

  NORTH = HEADING.NORTH, SOUTH = HEADING.SOUTH, EAST = HEADING.EAST, WEST = HEADING.WEST;

  TARGETS = [[1, 6], [1, 11], [2, 4], [3, 9], [5, 2], [6, 12], [7, 5], [8, 10], [9, 1], [9, 14], [10, 4], [10, 11], [12, 6], [13, 10], [14, 2], [14, 12]];

  WALLS = [[[0, 4], SOUTH], [[0, 6], EAST], [[0, 11], EAST], [[0, 13], SOUTH], [[1, 5], SOUTH], [[1, 11], SOUTH], [[1, 14], EAST], [[2, 3], SOUTH], [[2, 4], EAST], [[2, 13], SOUTH], [[3, 0], EAST], [[3, 8], SOUTH], [[3, 9], EAST], [[5, 2], SOUTH], [[5, 2], EAST], [[5, 15], EAST], [[6, 5], EAST], [[6, 7], EAST], [[6, 8], EAST], [[6, 12], EAST], [[6, 12], SOUTH], [[7, 5], SOUTH], [[7, 6], SOUTH], [[7, 8], SOUTH], [[7, 10], EAST], [[8, 1], EAST], [[8, 6], SOUTH], [[8, 7], EAST], [[8, 8], SOUTH], [[8, 8], EAST], [[8, 9], SOUTH], [[9, 1], SOUTH], [[9, 13], SOUTH], [[9, 14], EAST], [[10, 0], EAST], [[10, 4], EAST], [[10, 4], SOUTH], [[10, 11], EAST], [[10, 11], SOUTH], [[11, 6], EAST], [[11, 15], EAST], [[12, 5], SOUTH], [[12, 10], EAST], [[13, 9], SOUTH], [[13, 12], EAST], [[14, 1], SOUTH], [[14, 2], EAST], [[14, 12], SOUTH], [[15, 4], SOUTH], [[15, 8], SOUTH]];

  OPPOSITE_SIDES = {};

  OPPOSITE_SIDES[NORTH] = SOUTH;

  OPPOSITE_SIDES[EAST] = WEST;

  OPPOSITE_SIDES[SOUTH] = NORTH;

  OPPOSITE_SIDES[WEST] = EAST;

  makeWallPair = function(board, coord, side) {
    var oppositeSide, otherCoord;
    board.squares[coord[0]][coord[1]].push(side);
    otherCoord = nextCoord(coord, side);
    oppositeSide = OPPOSITE_SIDES[side];
    return board.squares[otherCoord[0]][otherCoord[1]].push(oppositeSide);
  };

  module.exports = function(board) {
    var coord, i, len, ref1, side;
    for (i = 0, len = WALLS.length; i < len; i++) {
      ref1 = WALLS[i], coord = ref1[0], side = ref1[1];
      makeWallPair(board, coord, side);
    }
    return board.possibleTargetLocations = TARGETS;
  };

}).call(this);
