// Generated by CoffeeScript 1.9.3
(function() {
  var _, random;

  _ = require('underscore');

  module.exports = random = {
    int: function(max, exclude) {
      if (exclude == null) {
        exclude = [];
      }
      return Math.floor(Math.random() * max);
    },
    coord: function(width, height) {
      return [random.int(width), random.int(height)];
    },
    choice: function(arr) {
      return arr[random.int(arr.length)];
    },
    coordExcluding: function(width, height, exclusions) {
      var coord, isExcluded;
      isExcluded = function(coord) {
        return _.any(exclusions, function(ec) {
          return coord[0] === ec[0] && coord[1] === ec[1];
        });
      };
      coord = random.coord(width, height);
      while (isExcluded(coord)) {
        coord = random.coord(width, height);
      }
      return coord;
    }
  };

}).call(this);
